
server:
  port: 9999
management:
  health:
    mail:
      enabled: false
info:
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"

spring:
  dev_model: false
  output:
    ansi:
      enabled: always
  messages:
    basename: /i18n/message
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bbex?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: photoadmin
    password: Photo123456
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: photo
      authentication-database: photo
      username: photoadmin
      password: photoadmin
      reactive-repositories:
        enabled: true

  redis:
    #    password: foobaredbbexONE123
    host: 127.0.0.1
    port: 6379

  kafka:
    producer:
      value-serializer: com.biao.kafka.interceptor.CustomerJsonSerializer
      properties:
        interceptor.classes: com.biao.kafka.interceptor.KafkaMessageIdGenerator
    bootstrap-servers:
      - 127.0.0.1:9092
    consumer:
      value-deserializer: com.biao.kafka.interceptor.CustomerJsonDeserializer
      group-id: webSocket
      auto-offset-reset: earliest
      properties:
        partitioner.expair : 0-7,8-15,16-23,24-31,32-39,40-47,48-55,56-63
        spring:
          json:
            trusted:
              packages: com.biao.listener.kafka,com.biao.kafka.interceptor,com.biao.pojo
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

mybatis:
  typeAliasesPackage: com.biao.entity
  configLocation: classpath:mybatis/mybatis-config.xml

relayPrizeTime: 20
biao:
  netty:
    websocket:
      port : 9999
      maxThreads: 16
  order:
    delayTime : 30

  mail[0]:
    password: Service123456
    username: service@coceu.com
    alias: coceu
    sendname: service@coceu.com
    auth: true
    host: smtp.coceu.com
    openssl: true
    port: 25

password:
  resetUrl: https://www.biao.one/reset/mail
register:
  switch: 1

inviteCodes:

google:
  domain: biao


coin:
  main:
    list:
      - USDT
aliyun:
  authenticatesig:
    accessKeyId:
    accessKeySecret:

logging:
  level:
    root: info
    org.springframework.boot: info
    org.apache.ibatis: info
    com.bbex.bonuspoint: info
    com.bbex.lottery: info
    com.bbex: debug
    io.netty: info
  path: "./logs"
  config: classpath:logback.xml


