## 访问的交易网地址；
url: http://127.0.0.1:8083
## 地址信息；
token: 09fabb70bcb84a28bc98b82424ff99dd
## 交易时间定义 s;
tradeTime: 1
##获取volume的工厂算法；
volumeFactory: com.bbex.robot.RandomRobotVolume
##获取price的工厂算法；
priceFactory: com.bbex.robot.RandomRobotPrice
### jdbcurl prod
jdbcUrl: jdbc:mysql://192.168.1.80:3306/bbex-test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
jdbcUser: root
jdbcPass: 123456
#jdbcUrl: jdbc:mysql://rm-t4nl1jg9gi7bbe9w6.mysql.singapore.rds.aliyuncs.com:3306/bbex-test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#jdbcUser: szwd_db
#jdbcPass: Hrsd@2018Admin&
### 可以用于登录的帐号密码；
loginUser: 123@qq.com
loginPass: P8XEZh4dLwWWq6i4UzNQiVmLvwgZf8C+igIUzvF4ROWS1yfKmhMAx431yTCBFVCakVEXttJUsmdN0DJ/hrKLTZeCQ0MXxjOruPyV5EWimKG4EBwQQSsP1RTv7NBIk0LR/y8dUgRlz7kJ59gcHY1TmZOoZx55hFGcXwImMsL5ifM=
apiKey: 069GLa6opE1aXbWwOrcdxUi6ZdkbC61wiTihfxSDyIb7P8p0rbgKKTcqLoEVJSRy
skey: u3kni9Rfa1WA0cWfVYlMALafGydXi4bXAiWuXo6iAS5CMQqxeFRnc0wTCmMWLFOj