server:
  port: 8081
spring:
  datasource:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://rm-j6c6mdh161ts3o52bco.mysql.rds.aliyuncs.com:3306/bbex?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useSSL=false
            username: photoadmin
            password: Photo123456
            hikari:
              maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
              maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  data:
    mongodb:
      host: dds-j6c4cb1c77b752a41823-pub.mongodb.rds.aliyuncs.com
      port: 3717
      database: photo
      authentication-database: photo
      username: photoadmin
      password: photoadmin
      reactive-repositories:
        enabled: true
  redis:
    password: foobaredbbexONE123
    host: 47.244.153.103
    port: 6379


  kafka:
    producer:
      value-serializer: com.biao.kafka.interceptor.CustomerJsonSerializer
      properties:
          interceptor.classes: com.biao.kafka.interceptor.KafkaMessageIdGenerator
    bootstrap-servers:
      - 47.244.153.103:9092
    consumer:
      value-deserializer: com.biao.kafka.interceptor.CustomerJsonDeserializer
      group-id: kline
      auto-offset-reset: earliest
      properties:
        partitioner.expair : 0-7,8-15,16-23,24-31,32-39,40-47,48-55,56-63
        spring:
          json:
            trusted:
              packages: com.biao.listener.kafka,com.biao.kafka.interceptor,com.biao.pojo
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false


mybatis:
  type-aliases-package: com.biao.binance.config
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: info
        org.springframework.boot: error
        org.apache.ibatis: info
        com.bbex.bonuspoint: error
        com.bbex.lottery: error
        com.bbex: debug
        io.netty: info
    path: "./logs"
    config: classpath:logback.xml

