management:
  health:
    mail:
      enabled: false
info:
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
spring:
  dev_model: false
  output:
    ansi:
      enabled: always
  profiles:
    active: test



    