server:
 address: 0.0.0.0
 port: 8087

management:
  health:
    mail:
      enabled: false

spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-j6c6mdh161ts3o52bco.mysql.rds.aliyuncs.com:3306/bbex?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: photoadmin
      password: Photo123456
      hikari:
        maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
        maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  data:
    mongodb:
        host: dds-j6c4cb1c77b752a41823-pub.mongodb.rds.aliyuncs.com
        port: 3717
        database: photo
        authentication-database: photo
        username: photoadmin
        password: photoadmin
        reactive-repositories:
                enabled: true

  redis:
    password: foobaredbbexONE123
    host: 47.244.153.103
    port: 6379
mybatis:
    typeAliasesPackage: com.biao.entity
    configLocation: classpath:mybatis/mybatis-config.xml
omni:
    rpc:
      username: wpybtc
      password: wpybtc
      uri: http://127.0.0.1:18111
      sendAddr: 1ELQJ73re7ZS1D5TwBgzYHEjpfhxuYub3D
      collectAddr: 1ELQJ73re7ZS1D5TwBgzYHEjpfhxuYub3D
      feeAddr: 1ELQJ73re7ZS1D5TwBgzYHEjpfhxuYub3D
      collectFee: 0.0002
      coinId:
      syncTime: 300
      sendTime: 300
      collectTime: 300
generateAddress: 1
inviteCodes:
user:
  config:
    lockLength: 24
  coin-volume-bill:
    #     执行的节点数量
    needs: 1
    #      当前是几号节点，不要重复哦.
    need: 1
    #      执行时间S
    time: 5
    #是否启动task;
    taskFlag: true
logging:
    level:
        root: info
        org.springframework.boot: info
        org.apache.ibatis: info
        com.bbex.bonuspoint: info
        com.bbex.lottery: info
        com.bbex: info
    path: "./logs"
